### ISSUE TITLE
Windows App Runtime crashes application due to the bootstrapper not initializing.

### ISSUE THREAD

**Issue by Aetopia** [OpenSpartan/openspartan-workshop#1]
OpenSpartan crashes upon launching.
I also tried reinstalling but no success there.

Upon checking the event viewer:

![image](https://github.com/OpenSpartan/openspartan-workshop/assets/41850963/fced4e36-9856-4d88-a176-8bef44405526)

![image](https://github.com/OpenSpartan/openspartan-workshop/assets/41850963/20308fc2-47bc-4e10-8e38-7b56d3eef427)

Apparent, I found another instance of this same exact issue:
https://github.com/microsoft/WindowsAppSDK/discussions/3444

They linked how to [deploy the Windows App SDK for an unpackaged app](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps).

I decided to install packaged, unpackaged and redistributables for the Windows App Runtime onto my machine and it still crashes with that error message.

Windows Build Information:
![image](https://github.com/OpenSpartan/openspartan-workshop/assets/41850963/c386b85f-b04a-4b82-a192-613f41f4ad2f)

**Comment by dend** [comment]
@Aetopia are you using [Windows 10 IoT Enterprise LTSC](https://learn.microsoft.com/windows/iot/iot-enterprise/whats-new/windows-iot-enterprise-ltsc)? I will need to test how the application will work there (I only looked at consumer OS releases - 10 and 11), but _generally_ I assume that those are heavily stripped down versions of Windows that might not have all the more modern components.

**Comment by Aetopia** [comment]
> @Aetopia are you using [Windows 10 IoT Enterprise LTSC](https://learn.microsoft.com/windows/iot/iot-enterprise/whats-new/windows-iot-enterprise-ltsc)? I will need to test how the application will work there (I only looked at consumer OS releases - 10 and 11), but _generally_ I assume that those are heavily stripped down versions of Windows that might not have all the more modern components.

Yes, I am using Windows 10 IoT Enterprise LTSC, it doesn't have all of the pre-installed UWP apps that come with consumer releases.

But the store can be restored using `wsreset -i` and then can be used normally with the store.

**Comment by Aetopia** [comment]
Just tested on my PC, it works!
![image](https://github.com/OpenSpartan/openspartan-workshop/assets/41850963/ceab38c3-123b-4aa2-a29b-0f89509d234b)

Looks like some issue on my laptop.

**Comment by Aetopia** [comment]
![image](https://github.com/OpenSpartan/openspartan-workshop/assets/41850963/3430abce-e4bb-4cd1-b00c-1d059d14315d)
I was able to add my account now its stuck here.

**Comment by Aetopia** [comment]
![image](https://github.com/OpenSpartan/openspartan-workshop/assets/41850963/e238dc84-d527-4c12-9a28-fb445daa1852)
It works!

**Comment by Aetopia** [comment]
I am gonna close this issue, the launch issue seems to be something from my end.
Also great work on this!
