### ISSUE TITLE
"This application requires the App Windows Runtime Version 1.5," when I have a newer version installed

### ISSUE THREAD

**Issue by L3monP3pp3r** [OpenSpartan/openspartan-workshop#50]
### Issue

When trying to open the program for the first time after installation, I receive the prompt, "This application requires the App Windows Runtime Version 1.5," when I have the latest runtime installed.

### Screenshot

![Screenshot 2024-09-26 202714](https://github.com/user-attachments/assets/12c0f738-7cf6-4482-bf84-3ee33255584e)

### Relevant (?) Information

**Windows Version:** Windows 11 Beta 22635.4225 ni release
**OpenSpartan Workshop Version:** 1.0.8
**Event Viewer Error:** Event 22, Windows App Runtime - Package dependency criteria could not be resolved.

### Things I have tried:

- Downloading an older 1.5 installer from the [Archive of Windows App SDK downloads](https://learn.microsoft.com/en-za/windows/apps/windows-app-sdk/downloads-archive)

- Removing all Appx policies in regedit : HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Appx, restarting, and then redownloading the latest Windows App SDK

### What worked

Unfortuntately, nothing yet. Will update if I have success.

**Comment by dend** [comment]
@L3monP3pp3r - try downloading the latest release ([1.0.9](https://github.com/OpenSpartan/openspartan-workshop/releases/tag/1.0.9)) and see if you can still repro the issue.

**Comment by L3monP3pp3r** [comment]
1.0.9 works fine, thanks! Not sure how I ended up with 1.0.8. Currently getting a few strange values while I wait for the data to import but it should all sort by the time it's finished

Been wanting a native stat tracker app for ages, can't believe I stumbled upon this from a completely unrelated Reddit comment. Thanks for all your work.

**Comment by dend** [comment]
Excellent, thanks for keeping me posted about this issue, @L3monP3pp3r - feel free to reach out if you run into any problems.
