### ISSUE TITLE
Stuck at "Loading match details"

### ISSUE THREAD

**Issue by YUGENIWNL** [OpenSpartan/openspartan-workshop#6]
It got stuck like this for ~40 min. I launched program at 9:00 and it went to 1668 of 10285 in 5 hours

![image](https://github.com/OpenSpartan/openspartan-workshop/assets/161837413/bc2b3644-b30d-4311-83ee-1a5b74460cef)

**Comment by dend** [comment]
@YUGENIWNL is the number progressing, though? 5 hours for 1,668 matches is not expected.

**Comment by YUGENIWNL** [comment]
After relaunch it now progressing but it still very slow (it running ~6 hours now). I have decent PC (4K@144-capable in Infinite) and gigabit fiber, if it matters

![image](https://github.com/OpenSpartan/openspartan-workshop/assets/161837413/224a000f-b414-48a9-a3fb-cf2f09d86fb6)

**Comment by dend** [comment]
Seems like an abnormally long time to get all the matches. The PC specs likely don't matter here - my _hunch_ is that because we're querying matches _way in the past_ they are not cached on the server and it takes longer to get the data. I am currently looking at ways to parallelize this a bit. Stay tuned.

**Comment by YUGENIWNL** [comment]
Thanks! I happy to provide logs if needed, turned it On

![image](https://github.com/OpenSpartan/openspartan-workshop/assets/161837413/c32ab926-6bf2-4abb-a449-4c004536aae1)

**Comment by dend** [comment]
Thanks @YUGENIWNL. If you go to `%LOCALAPPDATA%\OpenSpartan.Workshop\logs`, grab the _latest_ file in the folder and attach it to a response.

**Comment by YUGENIWNL** [comment]
[2024-03-02_00_AKELUS-02082024.txt](https://github.com/OpenSpartan/openspartan-workshop/files/14466015/2024-03-02_00_AKELUS-02082024.txt)

**Comment by dend** [comment]
Should be fixed in https://github.com/OpenSpartan/openspartan-workshop/releases/tag/1.0.2, your logs actually helped me pinpoint another bug.

**Comment by YUGENIWNL** [comment]
I just installed 1.0.2 but it says 1.0.1 in settings. I also updated .net because it wont even let me launch the program so i think it is just mislabeled as 1.0.1

![image](https://github.com/OpenSpartan/openspartan-workshop/assets/161837413/f0539b44-7bb5-4dba-9c96-3c242e526d33)

Its significantly faster now, ~1 sec per match

![image](https://github.com/OpenSpartan/openspartan-workshop/assets/161837413/0c23284a-fe3f-4a9f-a692-c5e56f59db73)

**Comment by dend** [comment]
That shouldn't be the case @YUGENIWNL, but I will file a different bug to track upgrade scenarios.

![image](https://github.com/OpenSpartan/openspartan-workshop/assets/1389609/c83dccb3-0fbc-4144-b2de-c3dc1348ba61)

Try fully uninstalling and then installing 1.0.2.

**Comment by dend** [comment]
@YUGENIWNL - actually, I pushed a new 1.0.2 release that amends the previous one. Remove the old version and install 1.0.2 from scratch as a clean release.

**Comment by dend** [comment]
Installation should work properly now, starting with 1.0.3.
